### PR TITLE
fix(sessions): make user cookie persistant

### LINKED ISSUE #208: Need to re-login at every app launch
Openwhyd's ios app seems to not persist sessions anymore.

Reported by Petit Oai, on [Facebook](https://www.facebook.com/groups/openwhyd/permalink/2362354174046128/?comment_id=2371280306486848&reply_comment_id=2371905266424352&comment_tracking=%7B%22tn%22%3A%22R%22%7D):

> J'ai remarqué aussi que depuis quelques temps, l'appli ne conserve plus mon identifiant et mon mot de passe. Je dois les ressaisir à chaque ouverture. Il me semble que ce n'était pas le cas avant, mais je ne suis plus sûre.

Probably caused by the fact that the cookies have been generated by `express-session` instead of our custom code since we migrated the back-end to Express.js. (https://github.com/openwhyd/openwhyd/issues/122)

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/76930926-need-to-re-login-at-every-app-launch?utm_campaign=plugin&utm_content=tracker%2F41430033&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F41430033&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by adrienjoly**
Closes #208.

What does this PR do / solve?
-----------------------------

User needs to login again, everytime they restarts their browser. (including Openwhyd's iOS and Electron apps)

Overview of changes
-------------------

Specify a `maxAge` for cookies, so that they don't become browser-session-based by default.

How to test this PR?
--------------------

1. open an openwhyd session by logging in
2. shut down your web browser, then restart it
3. you should still be connected to your openwhyd account

### CODE REVIEW

**Comment by adrienjoly** [comment]
References:

- https://www.npmjs.com/package/express-session#cookiemaxage
- https://www.npmjs.com/package/connect-mongo#session-expiration

File: app.js [hunk 1]
```diff
@@ -144,16 +144,16 @@ function makeMongoUrl(params) {
 }
 
 function start() {
-  var myHttp = require('./app/lib/my-http-wrapper/http');
+  const myHttp = require('./app/lib/my-http-wrapper/http');
```
Comment (adrienjoly) [inline app.js]: unrelated change. #boyscoutrule
